FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

COPY pom.xml .
RUN mvn -q dependency:go-offline

ENV SPRING_DEVTOOLS_RESTART_ENABLED=true
ENV SPRING_PROFILES_ACTIVE=dev

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
